// GLOBAL TYPES
export const SET_DRAG_ITEM = "SET_DRAG_ITEM";
export const APPEND_SHAPE_LIST = "APPEND_SHAPE_LIST";
export const UPDATE_SHAPE_LIST = "UPDATE_SHAPE_LIST";

export const APPEND_ASSIST_LINE_LIST = "APPEND_ASSIST_LINE_LIST";
export const CLEAR_ASSIST_LINE_LIST = "CLEAR_ASSIST_LINE_LIST";