// GLOBAL TYPES
export const SET_DRAG_ITEM = "SET_DRAG_ITEM";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const CLEAR_SELECTED_ITEM = "CLEAR_SELECTED_ITEM";
export const APPEND_SHAPE_LIST = "APPEND_SHAPE_LIST";
export const UPDATE_SHAPE_LIST = "UPDATE_SHAPE_LIST";

export const APPEND_ASSIST_LINE_LIST = "APPEND_ASSIST_LINE_LIST";
export const CLEAR_ASSIST_LINE_LIST = "CLEAR_ASSIST_LINE_LIST";
export const CLEAR_RESIZABLE_BORDER = "CLEAR_RESIZABLE_BORDER";

export const SET_WORKSPACE_STATE = "SET_WORKSPACE_STATE";
export const CLEAR_WORKSPACE_STATE = "CLEAR_WORKSPACE_STATE";